PUT http://localhost:3000/api/tickets/65e1b4d4a9f7127ba368713b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWUwYzRhZTI1Y2Q1ZmY4MTM3NDg0ZGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwOTI5MDQ0M30.xdsoNskOUiisvy6MA-Vvk37igHHjoYODTvCg79FKdtM

{
  "description": "Updated description",
  "priority": "high"
}

